{
"listen":     "127.0.0.1:8080",
"database":   "collections.db",
"static":     "static",
"debug":      false,
"proxy":      false,
"tls":        true,
"tls_listen": "127.0.0.1:8888",
"cert":       "",
"key":        ""
}