{
"listen":     "127.0.0.1:8080",
"database":   "/var/lib/collectionDB/collections.db",
"templates":  "/etc/collectionDB/templates/**/*.html",
"debug":      false,
"proxy":      false,
"tls":        true,
"tls_listen": "127.0.0.1:8888",
"cert":       "",
"key":        ""
}