{
"listen":     "127.0.0.1:8080",
"database":   "/var/lib/collectionDB/collections.db",
"static":     "/etc/collectionDB/static",
"debug":      false,
"proxy":      false,
"tls":        false,
"tls_listen": "127.0.0.1:8888",
"cert":       "",
"key":        ""
}